### ISSUE TITLE
Perl 5.10 support?

### ISSUE THREAD

**Issue by phochste** [jorol/MARC-Parser-RAW#1]
Hi Johan is 5.12 really a must? We have still some CentOS 6.X systems around.

**Comment by jorol** [comment]
Hi Patrick,

Dist::Milla requires 5.12, see https://github.com/miyagawa/Dist-Milla/blob/master/cpanfile, the module itself should run on older Perl versions. I'm not shure what I should specify in the `cpanfile`, the minimum Perl version required for buillding or running the module?

Grüße

**Comment by phochste** [comment]
Does cpan/cpanm run Dist::Milla to build/install when available? I guess Dist::Milla always provides a Build.PL for backwards compatability.

**Comment by jorol** [comment]
No, I think the install is done by the Build or Make file. But Dist::Milla is needed to build/release the distribution. Should this dependency be in the cpanfile or not?

**Comment by phochste** [comment]
The cpanfile should reflect minimal requirements to run and test the system.

**Comment by jorol** [comment]
Ok, will fix that and upload a new version.

**Comment by jorol** [comment]
fixed in release 0.03
